kiss: ignore libraries with RPATH in dependency detector
kiss-community/kiss pull request #69
Opened 2022-09-07 13:11 UTC by git-bruh

2022-09-07 13:11 UTC, git-bruh commented
@illiliti

2022-09-07 15:48 UTC, illiliti requested changes

2022-09-07 15:48 UTC, illiliti commented on kiss
> +        ldd="$(ldd -- "$pkg_dir/$repo_name$_file" 2>/dev/null)" || continue
Remove quoting: ""

2022-09-07 15:48 UTC, illiliti commented on kiss
> +                break # Found RPATH which shouldn't be ignored
kiss doesn't have inline comments. we should keep it that way

2022-09-07 15:48 UTC, illiliti commented on kiss
> +    for path; do
Remove `;`

2022-09-12 15:59 UTC, git-bruh commented
Oh I missed your replies to my messages on IRC somehow. The other way is to get dirname of the interpreter and use that as the default search path but that's as unportable as this solution is

Also I feel it doesn't matter that much cuz let's say /usr/lib or /lib aren't in the default search path. Then it's quite likely that nothing will ever be installed there either

2022-09-16 13:17 UTC, merged